export const ActionTypes = {
    MOVIES_LOADING:"MOVIES_LOADING",
    MOVIES_SUCCES:"MOVIES_SUCCES",
    MOVIES_ERROR:"MOVIES_ERROR",
    GENRES_LOADING:"GENRES_LOADING",
    GENRES_SUCCESS:"GENRES_SUCCESS",
    GENRES_ERROR:"GENRES_ERROR",
};